Include /etc/proftpd/modules.conf
UseIPv6 off
ServerName "Servidor FTP"
ServerType standalone
DeferWelcome off
MultilineRFC2228 on
DefaultServer on
ShowSymlinks on
TimeoutNoTransfer 600
TimeoutStalled 600
TimeoutIdle 1200
Port 21
MasqueradeAddress 127.0.0.1
PassivePorts 60000 60010

DefaultRoot ~
RequireValidShell off
Include /etc/proftpd/tls.conf

<Anonymous /srv/ftp_anonimo>
  User ftp
  Group nogroup
  UserAlias anonymous ftp
  RequireValidShell off
  MaxClients 10
  <Directory *>
    <Limit WRITE>
      DenyAll
    </Limit>
  </Directory>
</Anonymous>